name: Auto Release
on:
  workflow_dispatch:
  push:

jobs:
  build-py39:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Install Python lib
        run: |
          pip install -r requirements.txt

      - name: Zip files
        run: Compress-Archive . playground.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.md
          files: |
            playground.zip
            CHANGELOG.md

