name: test
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  jobtest:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cache python packages
        uses: actions/cache@v2
        if: startsWith(runner.os, 'Windows')
        id: cache-pip
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        
      - name: dir
        run: dir $(py -m pip cache dir)

      - name: dir
        run: dir ~\AppData\Local\pip\Cache

      - name: Install Python lib
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          pip install -r requirements.txt

      - name: dir
        run: dir $(py -m pip cache dir)

      - name: Show Python lib
        run: pip list