name: test
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-2022
    if: startsWith(github.ref, 'refs/heads/')
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: test
        run: python test.py


