name: test
on:
  push:
    branches:
      - main

jobs:

  jobtest:
    runs-on: windows-2022
    steps:
      - name: Install CODING Generic
        run: npm install coding-generic -g
        
      - name: test CODING Generic
        run: coding-generic

