name: test
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: test
        run: python test.py

  release2:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: test
        run: python test.py

